// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/betNevS/Go-000/Week04/internal/biz"
	"github.com/betNevS/Go-000/Week04/internal/data"
)

// Injectors from wire.go:

func InitUserRegisterCase() *biz.UserRegisterCase {
	userRepo := data.NewUserRepo()
	userRegisterCase := biz.NewUserRegisterCase(userRepo)
	return userRegisterCase
}
